apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: dashboard-patch.yaml
labels:
  - pairs:
      course.teko.ch/block: "04"
    includeSelectors: false
