alertmanager:
  enabled: false

defaultRules:
  create: false

grafana:
  enabled: true
  adminPassword: delivery
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 384Mi

prometheus:
  prometheusSpec:
    retention: 2h
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 768Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 500m
      memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 48Mi
    limits:
      cpu: 200m
      memory: 128Mi

nodeExporter:
  enabled: false

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
