apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: food-delivery
spec:
  template:
    spec:
      containers:
        - name: rabbitmq
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 15
            failureThreshold: 6
          livenessProbe:
            initialDelaySeconds: 120
            timeoutSeconds: 25
            failureThreshold: 6
          resources:
            limits:
              cpu: "2"
              memory: 768Mi
            requests:
              cpu: 200m
              memory: 256Mi
