apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../block-04-ingress
  - rabbitmq.yaml
  - workers.yaml
patches:
  - path: configmap-patch.yaml
  - path: control-api-patch.yaml
labels:
  - pairs:
      course.teko.ch/block: "05"
    includeSelectors: false
